[buid-system]
requires= ["setuptools>=42.0","wheel"]
buid-backend="setuptools.build_meta"

[tool.pytest.ini_options]
tests_paths=[
    "tests"
]

[tool.mypy]
mypy_path="src"
ignore_missing_imports=true
