training_pipeline_config:
  pipeline_name: src/deep_classifier
  artifact_dir: artifact

data_ingestion_config:
  data_ingestion_dir: data_ingestion
  dataset_download_url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"
  raw_data_dir: raw_data
  extracted_data_dir: extracted_data
  ingested_train_dir: train
  ingested_test_dir: test

prepare_base_model_config:
  prepare_base_model_dir: prepare_base_model
  base_model_dir: base_model
  base_model_file_name: base_model.h5
  updated_model_dir: updated_model
  updated_model_file_name: updated_model.h5
  params_image_size: 